# version removed (obsolete in Compose v2)
services:
  egl:
    container_name: egl
    hostname: egl
    # Change tag `latest` to Ubuntu versions such as `24.04`, use a persistent tag such as `24.04-20210101010101` to persist a certain container version
    image: xon-streaming-client:latest
    # Explicit GPU request for Compose v2 (non-Swarm)
    gpus: all
    ports:
    - '8080:8080'
    # Expose the port for the game launch agent
    - '5001:5001'
    # Internal TURN server settings
    - '3478:3478'
    - '65534-65535:65534-65535'
    - '3478:3478/udp'
    - '65534-65535:65534-65535/udp'
    stdin_open: true
    tty: true
    restart: unless-stopped
    # Allow Steam/Flatpak style sandboxes that require user namespaces
    security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
    cap_add:
    - SYS_ADMIN
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    tmpfs:
    - '/dev/shm:rw'
    volumes:
    # Mount a volume to persist the user's home directory.
    # This saves game data, Steam login tokens, and configurations.
    # To use a specific host path for a user (e.g., for user 'player1'), you can change the line below to:
    # - /path/to/player1_data:/home/ubuntu
    - egl-home-vol:/home/ubuntu
    # Ensure supervisord uses the updated configuration from the project
    - ./supervisord.conf:/etc/supervisord.conf:ro
    # Provide a static nginx.conf
    - ./nginx.conf:/etc/nginx/static-nginx.conf:ro
    # Mount a host directory containing large game files into the container.
    # The user should place their game installation files in a directory on the host (e.g., /data/games)
    # and update the path on the left side of the colon.
    - /data/games:/opt/games:ro
    # Uncomment the below line to disable network isolation for WebRTC connectivity, display `:20` and `:21` should not be used in the host, may show an error if disallowed by the cluster
#    network_mode: 'host'
    environment:
    - TZ=UTC
    # NVIDIA runtime hints for portability (toolkit will override when present)
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - DISPLAY_SIZEW=1920
    - DISPLAY_SIZEH=1080
    - DISPLAY_REFRESH=60
    - DISPLAY_DPI=96
    - DISPLAY_CDEPTH=24
    # Keep to default unless you know what you are doing with VirtualGL, `VGL_DISPLAY` should be set to either `egl[n]` or `/dev/dri/card[n]` only when the device was passed to the container
#    - VGL_DISPLAY=egl
    # User password of container
    - PASSWD=${PASSWD:-mypasswd}
    # Enable KasmVNC to stabilize 8080 while Selkies is being investigated (parameterized for permanence)
    - KASMVNC_ENABLE=false
    # Agent healthcheck
    - AGENT_PORT=5001
    - SELKIES_ENCODER=nvh264enc
    - SELKIES_ENABLE_RESIZE=true
    - SELKIES_VIDEO_BITRATE=8000
    - SELKIES_FRAMERATE=60
    - SELKIES_AUDIO_BITRATE=128000
#    - SELKIES_CONGESTION_CONTROL=true
    - SELKIES_ENABLE_BASIC_AUTH=false
#    - SELKIES_BASIC_AUTH_PASSWORD=mypasswd
    - SELKIES_ENABLE_HTTPS=false
    - SELKIES_TURN_PROTOCOL=udp
    - TURN_MIN_PORT=65534
    - TURN_MAX_PORT=65535
    - SELKIES_TURN_HOST=127.0.0.1
#    - SELKIES_HTTPS_CERT=/etc/ssl/certs/ssl-cert-snakeoil.pem
#    - SELKIES_HTTPS_KEY=/etc/ssl/private/ssl-cert-snakeoil.key
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5001/health && nc -z 127.0.0.1 8080 && nc -z 127.0.0.1 8081"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s
    # Number of threads for encoding frames with KasmVNC, default value is all threads
#    - name: KASMVNC_THREADS=0
    ###
    # Selkies parameters, for additional configurations see `selkies-gstreamer --help`
    ###
    # Change `SELKIES_ENCODER` to `x264enc`, `vp8enc`, or `vp9enc` if using software fallback without allocated GPUs or your GPU does not support `H.264 (AVCHD)` under the `NVENC - Encoding` section in https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
    # The following SELKIES_* variables are configured in the environment block above:
    # - SELKIES_ENCODER=x264enc
    # - SELKIES_ENABLE_RESIZE=false
    # - SELKIES_VIDEO_BITRATE=8000
    # - SELKIES_FRAMERATE=60
    # - SELKIES_AUDIO_BITRATE=128000
    # - SELKIES_ENABLE_BASIC_AUTH=false
    # - SELKIES_ENABLE_HTTPS=false
    # Initial video bitrate in kilobits per second, may be changed later within web interface
    #    - SELKIES_VIDEO_BITRATE=8000
    # Initial frames per second, may be changed later within web interface
    #    - SELKIES_FRAMERATE=60
    # Initial audio bitrate in bits per second, may be changed later within web interface
    #    - SELKIES_AUDIO_BITRATE=128000
    # Uncomment if network conditions rapidly fluctuate
    #    - SELKIES_CONGESTION_CONTROL=true
    # Enable Basic Authentication from the web interface
    #    - SELKIES_ENABLE_BASIC_AUTH=false
    # Defaults to `PASSWD` if unspecified
    #    - SELKIES_BASIC_AUTH_PASSWORD=mypasswd
    # Enable HTTPS web interface from inside the container
    #    - SELKIES_ENABLE_HTTPS=false
    # Volume mount trusted HTTPS certificate to new path for no web browser warnings
    #    - SELKIES_HTTPS_CERT=/etc/ssl/certs/ssl-cert-snakeoil.pem
    #    - SELKIES_HTTPS_KEY=/etc/ssl/private/ssl-cert-snakeoil.key
    ###
    # Uncomment and configure below to use a TURN server for improved network compatibility
    ###
#    - SELKIES_TURN_HOST=turn.example.com
#    - SELKIES_TURN_PORT=3478
    # Change to `tcp` if the UDP protocol is throttled or blocked in your client network, or when the TURN server does not support UDP
#    - SELKIES_TURN_PROTOCOL=udp
    # You need a valid hostname and a certificate from authorities such as ZeroSSL or Let's Encrypt with your TURN server to enable TURN over TLS
#    - SELKIES_TURN_TLS=false
    # Internal TURN server settings, do not uncomment other TURN server settings below this when using an internal TURN server
#    - TURN_MIN_PORT=65534
#    - TURN_MAX_PORT=65535
    # Provide only `SELKIES_TURN_SHARED_SECRET` for time-limited shared secret authentication or both `SELKIES_TURN_USERNAME` and `SELKIES_TURN_PASSWORD` for legacy long-term authentication, but do not provide both authentication methods at the same time
#    - SELKIES_TURN_SHARED_SECRET=n0TaRealCoTURNAuthSecretThatIsSixtyFourLengthsLongPlaceholdPlace
#    - SELKIES_TURN_USERNAME=username
#    - SELKIES_TURN_PASSWORD=mypasswd
    # TURN REST URI authentication, all TURN server settings above are ignored if enabled
#    - 'SELKIES_TURN_REST_URI=http://localhost:8008'

volumes:
  egl-home-vol:
